In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("emails.csv")

In [6]:
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
df.tail()

                                                   text  spam
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [8]:
df.shape

(5728, 2)

In [9]:
df.columns

Index(['text', 'spam'], dtype='object')

In [10]:
df = df [["text" , "spam"]]

In [11]:
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [13]:
df.rename(columns={"text": "label", "spam": "message"}, inplace=True)

In [14]:
df.head()

                                               label  message
0  Subject: naturally irresistible your corporate...        1
1  Subject: the stock trading gunslinger  fanny i...        1
2  Subject: unbelievable new homes made easy  im ...        1
3  Subject: 4 color printing special  request add...        1
4  Subject: do not have money , get software cds ...        1

In [15]:
df.head(3)

                                               label  message
0  Subject: naturally irresistible your corporate...        1
1  Subject: the stock trading gunslinger  fanny i...        1
2  Subject: unbelievable new homes made easy  im ...        1

In [16]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [17]:
df.drop_duplicates()

                                                  label  message
0     Subject: naturally irresistible your corporate...        1
1     Subject: the stock trading gunslinger  fanny i...        1
2     Subject: unbelievable new homes made easy  im ...        1
3     Subject: 4 color printing special  request add...        1
4     Subject: do not have money , get software cds ...        1
...                                                 ...      ...
5723  Subject: re : research and development charges...        0
5724  Subject: re : receipts from visit  jim ,  than...        0
5725  Subject: re : enron case study update  wow ! a...        0
5726  Subject: re : interest  david ,  please , call...        0
5727  Subject: news : aurora 5 . 2 update  aurora ve...        0

[5695 rows x 2 columns]

In [19]:
df.duplicated().sum()

np.int64(33)

to isey ham log pata karenge ki kitna hammm log ka duplicate values ha dataset me

In [21]:
df=df.drop_duplicates()

ye duplicated values  ko remove karta ha

In [22]:
df.duplicated().sum()

np.int64(0)

In [1]:
import re

In [2]:
example = "Free enetry in 2 a weklk !!! hurrah you won fa text 7373737"

In [3]:
example_clean = re.sub(r"[^a-z \s]" , "" , example)

In [4]:
print(example_clean)

ree enetry in  a weklk  hurrah you won fa text

In [10]:

df.columns = ['message', 'label']


df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-z\s]', '', str(x)))


print(df.head())

                                             message  label
0  ubject naturally irresistible your corporate i...      1
1  ubject the stock trading gunslinger  fanny is ...      1
2  ubject unbelievable new homes made easy  im wa...      1
3  ubject  color printing special  request additi...      1
4  ubject do not have money  get software cds fro...      1

In [12]:

df.columns = ['message', 'label']


df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-z\s]', '', str(x)))


print(df.head())

                                             message  label
0  ubject naturally irresistible your corporate i...      1
1  ubject the stock trading gunslinger  fanny is ...      1
2  ubject unbelievable new homes made easy  im wa...      1
3  ubject  color printing special  request additi...      1
4  ubject do not have money  get software cds fro...      1

In [13]:

df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-z\s]', '', str(x).lower()))

In [14]:

df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', str(x)))

In [16]:
import pandas as pd
import re


df = pd.read_csv('emails.csv')


df.columns = ['message', 'label']


df['message'] = df['message'].apply(lambda x: re.sub(r'[^a-z\s]', '', str(x).lower()))


print(df.head())

                                             message  label
0  subject naturally irresistible your corporate ...      1
1  subject the stock trading gunslinger  fanny is...      1
2  subject unbelievable new homes made easy  im w...      1
3  subject  color printing special  request addit...      1
4  subject do not have money  get software cds fr...      1

In [17]:
df.head()

                                             message  label
0  subject naturally irresistible your corporate ...      1
1  subject the stock trading gunslinger  fanny is...      1
2  subject unbelievable new homes made easy  im w...      1
3  subject  color printing special  request addit...      1
4  subject do not have money  get software cds fr...      1

In [18]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\aryan\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\aryan\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\aryan\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\aryan\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\aryan\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\aryan\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [19]:
import nltk

In [20]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [21]:
nltk.download("stopwords")

[nltk_data] Error loading stopword: Package 'stopword' not found in
[nltk_data]     index

False

In [22]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...

True

In [23]:
from nltk.tokenize import word_tokenize

In [29]:
sample = "Hitting Aryan is not a cup of tea for you"

In [30]:
sample_token = word_tokenize(sample)

In [43]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

stopword are vowels and a you are not req foer machine

In [32]:
print(sample_token)

['Hitting', 'Aryan', 'is', 'not', 'a', 'cup', 'of', 'tea', 'for', 'you']

In [36]:
from nltk.corpus import stopwords

In [38]:
import nltk
from nltk.corpus import stopwords


nltk.download('stopwords')


stop_words = set(stopwords.words('english'))


print(list(stop_words)[:10])

['before', 'above', 'down', "she's", "he'll", 'shan', 'so', 'we', 'wouldn', 'some']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\aryan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [40]:
stopwords = set(stopwords.words('english'))

In [46]:
df['message'] = df['message'].apply(lambda x: " ".join([word for word in word_tokenize(str(x)) if word not in stop_words]))

In [47]:
print (df["message"][2])

[ 'subject ' , 'unbelievable ' , 'new ' , 'homes ' , 'made ' , 'easy ' , 'im ' , 'wanting ' , 'show ' , 'homeowner ' , 'pre ' , 'approved ' , 'home ' , 'loan ' , 'fixed ' , 'rate ' , 'offer ' , 'extended ' , 'unconditionally ' , 'credit ' , 'way ' , 'factor ' , 'take ' , 'advantage ' , 'limited ' , 'time ' , 'opportunity ' , 'ask ' , 'visit ' , 'website ' , 'complete ' , 'minute ' , 'post ' , 'approval ' , 'form ' , 'look ' , 'foward ' , 'hearing ' , 'dorcas ' , 'pittman ' ]

In [48]:
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

stemmer = PorterStemmer()
df["message"] = df["message"].apply(
    lambda x: " ".join([stemmer.stem(word) for word in str(x).split()])
)


X = df["message"]
Y = df["label"]


vectorizer = TfidfVectorizer(max_features=3000)
X_vec = vectorizer.fit_transform(X)


X_train, X_test, Y_train, Y_test = train_test_split(
    X_vec, 
    Y, 
    test_size=0.20, 
    random_state=42
)


model = MultinomialNB()
model.fit(X_train, Y_train)





Y_pred = model.predict(X_test)


print("==MODEL OVERVIEW =======\n")

accuracy = accuracy_score(Y_test, Y_pred)
print(f"Overall Accuracy: {accuracy * 100:.2f}%\n")


print("--- Classification Report ---")
print(classification_report(Y_test, Y_pred))


print("--- Confusion Matrix ---")
print(confusion_matrix(Y_test, Y_pred))

========== MODEL OVERVIEW ==========

Overall Accuracy: 97.64%

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       856
           1       0.99      0.92      0.95       290

    accuracy                           0.98      1146
   macro avg       0.98      0.96      0.97      1146
weighted avg       0.98      0.98      0.98      1146

--- Confusion Matrix ---
[[852   4]
 [ 23 267]]

In [58]:
# 1. Apna normal email
text_to_test = "Hey David, just wanted to check if we are still on for the meeting at 3pm tomorrow? Let me know!"

print(f"--- STEP 1: Original Text ---\n{text_to_test}\n")

# 2. text saf
cleaned_text = clean_custom_email(text_to_test)
print(f"--- STEP 2: Cleaned Text ---\n{cleaned_text}\n")

# 3. Translate to numbers (CRITICAL Use sey.transform()!)
numbers_to_test = vectorizer.transform([cleaned_text])


print(f"--- STEP 3: Math Check ---")
print(f"Out of the 3000 words the model knows, it recognized {numbers_to_test.nnz} words in this email.\n")

# 5 final prediction model karega
prediction = model.predict(numbers_to_test)

print(f"--- STEP 4: Final Prediction ---")
if prediction[0] == 1:
    print(" PREDICTION: SPAM!")
else:
    print(" PREDICTION: NORMAL EMAIL (HAM)")

--- STEP 1: Original Text ---
Hey David, just wanted to check if we are still on for the meeting at 3pm tomorrow? Let me know!

--- STEP 2: Cleaned Text ---
hey david want check still meet pm tomorrow let know

--- STEP 3: Math Check ---
Out of the 3000 words the model knows, it recognized 10 words in this email.

--- STEP 4: Final Prediction ---
 PREDICTION: NORMAL EMAIL (HAM)

is model ka accuracy ha 97 per cent