In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
print("Shape of Dataset:", df.shape)

Shape of Dataset: (9994, 21)

In [6]:
print(df.dtypes)

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [7]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (9994, 21)
After: (9994, 21)

In [9]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [10]:


df["Profit_Status"] = np.where(
    df["Profit"] > 0,
    "Profit",
    "Loss"
)

df[["Profit","Profit_Status"]].head()

     Profit Profit_Status
0   41.9136        Profit
1  219.5820        Profit
2    6.8714        Profit
3 -383.0310          Loss
4    2.5164        Profit

In [11]:


df["High_Value_Order"] = np.where(
    df["Sales"] > 1000,
    "Yes",
    "No"
)

df[["Sales","High_Value_Order"]].head()

      Sales High_Value_Order
0  261.9600               No
1  731.9400               No
2   14.6200               No
3  957.5775               No
4   22.3680               No

In [12]:
def discount_category(discount):

    if discount <= 0.10:
        return "Low"

    elif discount <= 0.20:
        return "Medium"

    else:
        return "High"


df["Discount_Category"] = df["Discount"].apply(discount_category)

df[["Discount","Discount_Category"]].head()

   Discount Discount_Category
0      0.00               Low
1      0.00               Low
2      0.00               Low
3      0.45              High
4      0.20            Medium

In [13]:
def sales_category(sales):

    if sales < 100:
        return "Low Sales"

    elif sales < 500:
        return "Medium Sales"

    else:
        return "High Sales"


df["Sales_Category"] = df["Sales"].apply(sales_category)

df[["Sales","Sales_Category"]].head()

      Sales Sales_Category
0  261.9600   Medium Sales
1  731.9400     High Sales
2   14.6200      Low Sales
3  957.5775     High Sales
4   22.3680      Low Sales

In [15]:
total_sales = df["Sales"].sum()

print("Total Sales =", round(total_sales,2))

Total Sales = 2297200.86

In [18]:
total_profit = df["Profit"].sum()

print("Total Profit =", round(total_profit,2))

Total Profit = 286397.02

In [19]:
average_sales = df["Sales"].mean()

print("Average Sales =", round(average_sales,2))

Average Sales = 229.86

In [20]:
category_sales = df.groupby("Category")["Sales"].sum()

print(category_sales)

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [21]:
top_states = df.groupby("State")["Sales"].sum().sort_values(ascending=False)

print(top_states.head())

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Name: Sales, dtype: float64

In [23]:
top_customers = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False)

print(top_customers.head())

Customer Name
Sean Miller      25043.050
Tamara Chand     19052.218
Raymond Buch     15117.339
Tom Ashbrook     14595.620
Adrian Barton    14473.571
Name: Sales, dtype: float64

In [24]:
print(df["Profit_Status"].value_counts())

Profit_Status
Profit    8058
Loss      1936
Name: count, dtype: int64

In [25]:
print(df["High_Value_Order"].value_counts())

High_Value_Order
No     9526
Yes     468
Name: count, dtype: int64

In [26]:
print("Total Records :", len(df))

print("Total Sales :", round(df["Sales"].sum(),2))

print("Total Profit :", round(df["Profit"].sum(),2))

print("Average Sales :", round(df["Sales"].mean(),2))

print("Profit Orders :", (df["Profit_Status"]=="Profit").sum())

print("Loss Orders :", (df["Profit_Status"]=="Loss").sum())

print("High Value Orders :", (df["High_Value_Order"]=="Yes").sum())

Total Records : 9994
Total Sales : 2297200.86
Total Profit : 286397.02
Average Sales : 229.86
Profit Orders : 8058
Loss Orders : 1936
High Value Orders : 468

In [27]:
df.to_csv("Processed_Superstore.csv", index=False)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.